---
# handlers file for role-nrpe

- name: Handler nrpe reload
  ansible.builtin.service:
    name: nrpe
    state: reloaded
  when: ansible_os_family == 'RedHat'

- name: Handler nrpe reload Debian
  ansible.builtin.service:
    name: nagios-nrpe-server
    state: reloaded
  when: ansible_os_family == 'Debian'
